first_app/urls.py
from django.urls import path, include
from . import views

app_name="first_app"
urlpatterns=[
    path('first_app',views.index,name="index"),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin_app"),
    path('',include('home_page.urls')),
    path('',include('first_app.urls')),
    path('',include('second_app.urls')),
    path('',include('third_app.urls')),
    path('',include('fourth_app.urls'),)
]

fourth_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name="fourth_app"
urlpatterns = [
    path('fourth_app/home',views.index,name="index"),
    path('fourth_app/register',views.register,name="register"),
    path('fourth_app/login',views.user_login,name="user_login"),
    path('fourth_app/logout',views.user_logout,name="user_logout"),
]

home_page/urls.py
from django.urls import path, include
from . import views
app_name="home_page"
urlpatterns=[
    path('',views.index,name="index"),
]

second_app/urls.py
from django.urls import path, include
from . import views

app_name="second_app"
urlpatterns=[
    path('second_app',views.index,name="home"),
    path('second_app/sign_up',views.users,name="form"),
]

third_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name="third_app"
urlpatterns = [
    path('third_app/home',views.index,name="index"),
    path('third_app/other',views.other_page,name="other"),
]

first_app/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    top_name=models.CharField(max_length=100,unique=True)
    def __str__(self):
        return self.top_name

class WebPage(models.Model):
    topic=models.ForeignKey(Topic, on_delete=models.PROTECT)
    name=models.CharField(max_length=100,unique=True)
    url=models.URLField(unique=True)
    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name=models.ForeignKey(WebPage, on_delete=models.PROTECT)
    date=models.DateField() 

    def __str__(self):
        return str(self.date)

fourth_app/models.py
from tokenize import blank_re
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.PROTECT)
    #additional
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username

home_page/models.py
from django.db import models

# Create your models here.

second_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    email=models.EmailField(max_length=200,unique=True)
    

third_app/models.py
from django.db import models

# Create your models here.

fourth_app/forms.py
from socket import fromshare
from django import forms
from django.contrib.auth.models import User
from fourth_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

second_app/forms.py
from django import forms
from .models import User

class NewUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields= '__all__'

        

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Topic,WebPage,AccessRecord

# Create your views here.

def index(request):
    webpages_list=AccessRecord.objects.order_by('date')
    my_dict={
        'insert_here':"Hello I am inserted in this template fom first_app/views.py file",
        'access_records': webpages_list
    }
    return render(request,'first_app/index.html',context=my_dict)
 

fourth_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return render(request,"fourth_app/index.html",)


def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True
            return index(request)
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request, "fourth_app/registration.html",
                            {
                                "user_form":user_form,
                                "profile_form":profile_form,
                                "registered":registered,
                            }   )

@login_required
def user_logout(request):
    logout(request)
    return render(request,"fourth_app/index.html")

def user_login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        user= authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("fourth_app:index"))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login to the website and failed\n")
            print("Username: %s Password: %s "%(username,password))
            return HttpResponse("INVALID LOGIN CREDENTIALS")
    else:
        return render(request,"fourth_app/login.html", )

home_page/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request,'home_page/index.html',)
 

second_app/views.py
from django.shortcuts import render
from .forms import NewUserForm

# Create your views here.
def index(request):
    return render(request,'second_app/index.html')

def users(request):
    form=NewUserForm()
    if request.method=="POST":
        form=NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("Form Invalid")
    return render(request,'second_app/forms.html',{'form':form})
    

third_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request,'third_app/first_page.html',)
def other_page(request):
    return render(request,'third_app/second_page.html',)
 

templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First App Home Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'first_app/css/style.css' %}">
</head>
<body>
    <div class="container">
      <div class="jumbotron">
        <h2>Welcome to the first app of this website!</h1>
        <p class="lead">This app displays the records from the database and a image of Django from static files using template tagging in Django</p>
        <hr class="my-4">
        Enjoy your experience. 
      </div>
    </div>
    <br><br>
    
    <div class="container">
      <h3>Here are the records populated in the models connected to this html page</h3>
      {% if access_records %}
      <table>
          <thead>
              <th>Site Name</th>
              <th>Date accessed</th>
          </thead>
          {% for acc in access_records %}
          <tr>
              <td>{{acc.name}}</td>
              <td>{{acc.date}}</td>
          </tr>
          {% endfor %}
       </table>
       {% else %}
       <div>
          NO RECORDS TO DISPLAY
       </div>
       {% endif %}
  </div>
  <div class="container">
    <h3>Below is a picture of django himself!</h2>
    <img src="{% static 'first_app/images/django_guitar.jpeg' %}" alt="Could not fetch django_guitar.jpeg">

  </div>
</body>
</html>

templates/fourth_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fourth App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'fourth_app/style.css' %}">
</head>
<body>
    <!-- <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'fourth_app:index' %}">HOME</a></li>
                <li><a class="navbar-brand" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class="navbar-brand" href="{% url 'fourth_app:register' %}">REGISTER</a></li>

            </ul>
        </div>
    </nav> -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home_page:index' %}">PROJECT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'fourth_app:index' %}">HOME</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'fourth_app:register' %}">REGISTER</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}">ADMIN PAGE</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'fourth_app:user_logout' %}">LOGOUT</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'fourth_app:user_login' %}">LOGIN</a>
            </li>
            {% endif %}
          </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
    
</body>
</html>

templates/fourth_app/index.html
{% extends "fourth_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h2 class="display-4">Welcome to the fourth app of this website!</h2>
    <p class="lead">This app shows a demonstration of registration and login forms with changes and hashed passwords committed to the database</p>
    <hr class="my-4">
    <p>In case you are a new user to this website then click on the button below to register.</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url 'fourth_app:register' %}" role="button">Register</a>
    </p>
    <p>In case you have already registered, click on the button below to login. </p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url 'fourth_app:user_login' %}" role="button">Log In</a>
    </p>
</div>

{% endblock %}

templates/fourth_app/login.html
{% extends "fourth_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h2>Login here</h2>
    <form action="{% url 'fourth_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" name="" value="Login">
    </form>
</div>
{% endblock %}

templates/fourth_app/registration.html
{% extends "fourth_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    {% if registered %}
      <h2>Thank you for registering</h2>
    {% else %}
      <h2>Register Here</h2>
      <h3>Fill out the form below</h3>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" value="Register">
      </form>
    {% endif %}
</div>
{% endblock %}

templates/home_page/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website Home Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home_app/css/style.css' %}">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
        <h1 class="display-4">Welcome to this project website!</h1>
        <p class="lead">This is a demo website being developed by Arun Ramakrishnan using Django framework</p>
        <hr class="my-4">
        <p>In order to view first_app click on button below (basics, models data printing)</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'first_app:index' %}" role="button">First App</a>
        <p>In order to view second_app click on button below (forms, database updation)</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'second_app:home' %}" role="button">Second App</a>
        <p>In order to view third_app click on button below (url mappings, static templates)</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'third_app:index' %}" role="button">Third App</a>
        <p>In order to view fourth_app click on button below (registration, login forms)</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'fourth_app:index' %}" role="button">Fourth App</a>
        <p>In order to view the admin page of django, click on button below (user must be a registered superuser)</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'admin:index' %}" role="button">Admin Page</a>         
        </p>
      </div>
    </div>
 
</body>
</html>

templates/second_app/forms.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'second_app/css/style.css' %}">
    <title>Sign Up Form</title>
</head>
<body>
    <div class="container">
        <h1>Please sign up here</h1>
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>

</body>
</html>

templates/second_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'second_app/css/style.css' %}">
    <title>Second App Home Page</title>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
        <h2>Welcome to the second app of this website!</h1>
        <p class="lead">This page allows the user to sign up to the site and his/her details will be stored in the model connected to the form. </p>
        <hr class="my-4">
        <p>In order to view the changes in the database click on the button below. (User must be a registered superuser)</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'admin:index' %}" role="button">Admin page</a>
        </p>
      </div>
    </div>
    <div class="container">
        <h2>Click on the button below to sign up a new user to this website</h2>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'second_app:form' %}" role="button">Sign Up</a>
        </p>
    </div>
</body>
</html>

templates/third_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Third app</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">    
    <link rel="stylesheet" href="{% static 'third_app/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'third_app:index' %}">BASE</a></li>
                <li><a class="navbar-link" href="{% url 'third_app:other' %}">OTHER</a></li> 
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron">
            <h2 class="display-4">Welcome to the third app of the website!</h2>
            <p class="lead">This app gives us the experience of inheriting static templates of html and using it across various other html pages</p>
            <hr class="my-4">
            <p>In order to go back to home page click on the button below</p>
            <p class="lead">
              <a class="btn btn-primary btn-lg" href="{% url 'home_page:index' %}" role="button">Home Page</a>
            </p>
        </div>
    </div>
    <div class="container">
        {% block body_block %}
        {% endblock %}   
    </div>    
</body>
</html>

templates/third_app/first_page.html
<!DOCTYPE html>
{% extends "third_app/base.html" %}
{% block body_block %}
<h3>Welcome to the Home Page of the Third App</h3>
{% endblock %}

templates/third_app/second_page.html
<!DOCTYPE html>
{% extends 'third_app/base.html' %}
{% block body_block %}
<h3>Welcome to the other page of the Third App</h3>
{% endblock %}